// Derive the marketplace favicon set from the MAIN site's logo mark.
//
// The marketplace icon is deliberately the same mark as bitcoineconomy.ai — the
// robot head behind a ₿ — with exactly one change: the ₿ is recoloured from the
// site's Bitcoin orange (#f7931a family, the mark's flat #f39524) to The Market's
// violet (#8b7cff). Same robot, same geometry, same dark rounded square; only the
// section colour differs, which is the site's semantic triad (see ../CLAUDE.md).
//
// It was a plain purple ₿ glyph with no robot until 2026-08-10 — wrong mark, not
// just a wrong colour. Don't re-derive the icon from a font glyph; derive it from
// the mark, here.
//
// Generated (do not hand-edit): logo-mark-violet.png, favicon-32.png,
// apple-touch.png, favicon.svg. Run from this folder: node make-favicon.mjs
import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(__dirname, '..', 'public', 'images', 'logo-mark.png');

// Orange → violet, in HSV: rotate the hue of the orange-family pixels and scale
// their saturation/value by the ratio between the two brand colours. Working per
// pixel (rather than a flat colour swap) is what keeps the antialiased edges and
// the orange↔white boundary against the robot clean at 32px.
const SRC_HSV = { h: 32.9, s: 0.852, v: 0.953 };   // #f39524, the mark's flat orange
const DST_HSV = { h: 249.3, s: 0.514, v: 1.0 };    // #8b7cff, --agent

const rgbToHsv = (r, g, b) => {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min;
  let h = 0;
  if (d) {
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }
  return { h, s: max ? d / max : 0, v: max };
};

const hsvToRgb = (h, s, v) => {
  const c = v * s, x = c * (1 - Math.abs(((h / 60) % 2) - 1)), m = v - c;
  const [r, g, b] =
    h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] :
    h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return [r, g, b].map((n) => Math.round(Math.min(255, Math.max(0, (n + m) * 255))));
};

const { data, info } = await sharp(SRC).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
for (let i = 0; i < data.length; i += 4) {
  if (data[i + 3] === 0) continue;
  const { h, s, v } = rgbToHsv(data[i], data[i + 1], data[i + 2]);
  // Orange family only — the robot's whites (s≈0) and the black outline are left alone.
  if (s < 0.08 || h < 10 || h > 60) continue;
  const [r, g, b] = hsvToRgb(
    DST_HSV.h + (h - SRC_HSV.h) * 0.25,               // keep a trace of the original hue spread
    Math.min(1, s * (DST_HSV.s / SRC_HSV.s)),
    Math.min(1, v * (DST_HSV.v / SRC_HSV.v)),
  );
  data[i] = r; data[i + 1] = g; data[i + 2] = b;
}

const markBuf = await sharp(data, { raw: { width: info.width, height: info.height, channels: 4 } })
  .png()
  .toBuffer();
await sharp(markBuf).toFile(path.join(__dirname, 'logo-mark-violet.png'));

// Square icons: same recipe as the main site's scripts/make-logo-assets.mjs —
// the mark inset to 80% of a #0e0e0e square, so the two tabs sit side by side and
// read as the same icon in two colours.
const composeSquare = async (size, file) => {
  const inner = await sharp(markBuf)
    .resize({ width: Math.round(size * 0.8), height: Math.round(size * 0.8), fit: 'inside' })
    .png()
    .toBuffer();
  await sharp({ create: { width: size, height: size, channels: 3, background: '#0e0e0e' } })
    .composite([{ input: inner, gravity: 'center' }])
    .png()
    .toFile(path.join(__dirname, file));
};

await composeSquare(32, 'favicon-32.png');
await composeSquare(180, 'apple-touch.png');

// /favicon.svg is the fallback a browser asks for on any route that doesn't carry
// a <link rel="icon"> (the worker's .md and .json routes). Wrapping the 180px PNG
// keeps it pixel-identical to the tab icon at every size.
const b64 = (await fs.readFile(path.join(__dirname, 'apple-touch.png'))).toString('base64');
await fs.writeFile(
  path.join(__dirname, 'favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 180 180" role="img" aria-label="marketplace.bitcoineconomy.ai">
  <!-- The main site's logo mark (robot head behind a bitcoin symbol) with the
       bitcoin recoloured orange -> violet (#8b7cff, The Market's section colour).
       Generated by make-favicon.mjs - do not hand-edit. -->
  <image width="180" height="180" xlink:href="data:image/png;base64,${b64}"/>
</svg>
`,
);

console.log('Wrote logo-mark-violet.png, favicon-32.png, apple-touch.png, favicon.svg');
